### ISSUE TITLE
Python improvements

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#102]
This is just a list of some of the things that need to be done to improve/enhance the Python support:
1. Python data structure for ismrmrd meta data (and converters on the C++ side)
2. Python data structures for mricore data structures (Buckets, etc.)
3. Support for images with meta data in Python Gadgets and Instrumentation controller
4. Support for passing variables to Gadgets.

**Comment by hansenms** [comment]
All we have left here is:

Python data structures for mricore data structures (Buckets, etc.). @naegelejd, how much work would that be?

**Comment by naegelejd** [comment]
I will take a look at this and potentially present a first-pass implementation later today.

**Comment by naegelejd** [comment]
I've determined that it would be much easier if I was responsible for the C++/Python converters of these mricore data structures and someone else determined how they should look in Python. In the meantime, you can see what I've outlined on my branch in f2825b831dc514e97635518e5d39b1ba3f3ff810.
One problem is that none of these data structures really have any logic, they're just containers. In some ways it's challenging to represent these in Python. The way I've done it is useful for describing the data structure, but it's not *that* useful since you can just change the type of any member variable at any time by pointing it to a new object.

Anyway, there are a couple other things I haven't figured out, like how the `class IsmrmrdAcquisitionData` contains the following:
```c++
GadgetContainerMessage<ISMRMRD::AcquisitionHeader>* head_;
GadgetContainerMessage< hoNDArray< std::complex<float> > >* data_;
GadgetContainerMessage< hoNDArray< float > > * traj_;
```
which doesn't translate directly to Python because we don't need a `GadgetContainerMessage`. If we just replace each of these members in Python with `ismrmrd.AcquisitionHeader`, `numpy.array(dtype='complex64')`, and `numpy.array(dtype='float32')`, respectively, the `IsmrmrdAcquisitionData` becomes the same thing as an `ismrmrd.Acquisition`.

**Comment by inati** [comment]
Agree with the above.  They ARE just containers to make things easy to pass around and to group in a reasonable way.  We spent a lot of time working out the logic of the how the containers are laid out so that we can support a set of pipelines that can handle a wide range of applications.

A lot of it is there just for performance.  For example, the IsmrmrdAcquisitionData is there so that on the C++ side we don't need to do a memcpy.  

Functionally a bucket is a just a collection of acquisitions (head, data, and traj) - in two bins data_ and ref_ with some simple stats so that you don't have to read all the headers.  It should look kind of like that on the python side, but the underlying details are up in the air.

So yes, the right thing to do is to work through a couple of the gadgets and see how they should look on the python side.  Right now, the only thing we have is the sequence of three gadgets (e.g. default.xml) that is AcquisitionAccumulateTriggerGadget followed by SimpleRecon and then by ImageArraySplit.

I'm open to all suggestions here on how things should look on the python side.

@dchansen - could you chime in with any additional thoughts maybe related to how you think about the matlab equivalents?  I guess you only made a Buffer and not a bucket.

**Comment by hansenms** [comment]
@dchansen I think we can close this, right....super old.
