### ISSUE TITLE
Sporadic failure in docker images with python

### ISSUE THREAD

**Issue by dchansen** [gadgetron/gadgetron#1045]
So this is a fun one!

`external_python_bucket_example` and `external_buffer_example` will randomly fail (~10% chance) with a 
`Inconsistency detected by ld.so: dl-open.c: 881: _dl_open: Assertion '_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!` error.

Running with strace reveals that this is` libmkl_core.so` trying to dynamically link to` libmemkind.so` at runtime (not linktime), and failing. Presumably the intended behaviour is that MKL should look to see if libmemkind is available, and otherwise fall back to the system memory allocator.

The error does NOT appear in `external_python_acquistion_example`, nor in` external_equivalent example`. 
This suggests that the real issue is a race condition MKL in python, and MKL used in the NoiseAdjustGadget. Even when each is in their own separate process.

The issue has been confirmed with docker in a Fedora host system and on a Windows WSL2 host. 

Minmal reproducing example from the integration-test folder:

```bash
while : ; do python3 run_gadgetron_test.py cases/external_python_bucket_example.cfg; code=$?; echo $code; if [ $code -gt 0 ]; then break; fi ; done ; cat test/gadgetron.log  
````

A somewhat unsatisfying fix appears to be
`conda install -c intel memkind`

**Comment by hansenms** [comment]
I’ll take a look. Thanks for the suggested fix too, not sure I would find it all that unsatisfying if we can understand why it works.

**Comment by hansenms** [comment]
@dchansen having some fun with this;)

I can confirm the behavior you are are seeing (small note: the repro line you had above was not the right test, but the `external_python_buffer_example.cfg` does allow a repro.

I played around with the MKL stuff a bit and installed memkind, which indeed seems to do the trick. I have it running now for a while. However, on occasion, I will see another bug:

```
01-27 22:01:52.422 DEBUG [NoiseAdjustGadget.cpp:210] Measurement ID is 25135_461079_461084_37
01-27 22:01:52.422 INFO [Python.cpp:111] Started external Python module (pid: 14,553).
01-27 22:01:52.423 DEBUG [RemoveROOversamplingGadget.cpp:43] RemoveROOversamplingGadget:omp_set_num_threads(1) ... 
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  connect: Connection refused
01-27 22:01:52.860 DEBUG [ext. 14553 gadgetron.examples.recon_buffers] Starting external Python module 'gadgetron.examples' in state: [ACTIVE]
01-27 22:01:52.861 DEBUG [ext. 14553 gadgetron.examples.recon_buffers] Connecting to parent on port 40269
01-27 22:01:52.863 CRITICAL [ext. 14553 gadgetron.examples.recon_buffers] [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/conda/envs/gadgetron/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/gadgetron/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/gadgetron/lib/python3.9/site-packages/gadgetron/__main__.py", line 55, in <module>
    raise e
  File "/opt/conda/envs/gadgetron/lib/python3.9/site-packages/gadgetron/__main__.py", line 52, in <module>
    main(sys.argv[1:])
  File "/opt/conda/envs/gadgetron/lib/python3.9/site-packages/gadgetron/__main__.py", line 45, in main
    with connection.Connection(socket.create_connection(address, 30)) as conn:
  File "/opt/conda/envs/gadgetron/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/opt/conda/envs/gadgetron/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

It is pretty rare, but I think this bug is what we are seeing in the tests that fail with the external stuff (#1032). That one is extremely hard to repro. It is probably a different mechanism.

Not sure about the right fix here. Adding memkind seems like a pretty easy way to go, but I am also not totally sure why it fixes anything. The fact that it fails with dlopen could be some indication that both the python process and the main gadgetron process are trying to load MKL at the same time or some such thing and that having memkind around prevents the exact problem from occurring but without looking at that code in MKL it would be hard to tell. We could also try to go back and build Gadgetron against MKL in the revision before we introduced the conda build stuff to see if that does something different. 

I will put up a PR to add memkind (and I will update to latest version of MKL while I am tinkering with it). We can discuss if that is what we want to do.
