### ISSUE TITLE
boost filesystem lingking issue

### ISSUE THREAD

**Issue by Anais-A** [gadgetron/gadgetron#1064]
Hello, I hope I am posting this in the right place. 
I am trying to build a local Gadgetron on my ubuntu machine. 
When I am trying to build the project, I get an error : 

>[ 26%] Building CXX object core/writers/CMakeFiles/gadgetron_core_writers.dir/ImageWriter.cpp.o
>/usr/bin/ld: CMakeFiles/session_tests.dir/storage_test.cpp.o: in function `SessionsTest::SetUp()':
storage_test.cpp:(.text._ZN12SessionsTest5SetUpEv[_ZN12SessionsTest5SetUpEv]+0x12c): undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::filesystem::path const*, boost::system::error_code*)'

I tried many workarounds found online, but nothing worked. I have boost 1.71.0 installed using "sudo apt-get install libboost-all-dev"
Do you have a hint on haw to solve this problem?

Thank ou in advance,
Anaïs

**Comment by hansenms** [comment]
Thanks. Could you give us a bit more information about your setup (we will have some issue templates soon that should help collect this). What Linux distribution are you on? Version. What exact commands did you type to see this issue? Basically what steps would I need to take to reproduce this? Ideally including how you installed all your dependencies. Also, did you use to be able to build on that system? If so, what commit hash is working?

Boost 1.71 is pretty old, we currently build against 1.76, but I think it should work still. One hint in your error is that it is coming from the storage server (which is about to be removed). So I am wondering if you were able to build before that and it’s failing now. It may take us a bit of time to get there, but we will find the problem.

In the meantime I would encourage you to check out our Docker images or install with conda. We continuously check that so that would be your best up to date instructions.

And no worries about the right place to post. In general, if the software is broken or doesn’t build, it should be an issue so we can track it. Discussion is for broader discussions and getting him from peers, but it’s not widely used and not monitored as closely as the repo.

**Comment by apd47** [comment]
Not a solution, but a note: We've had similar issues recently given that gadgetron_ubuntu_2004_cuda11_cudnn8: latest includes Boost 1.71. This isn't the latest runtime or development image, and we should probably fix the package filter settings for the sidebar to show the proper docker images. 

That said, switching to the updated RT and Dev images might help, though neither have the same mix of residual dependencies for out-of-tree development as the older image sets.

**Comment by Anais-A** [comment]
Hi, thank you for your answers. I had this problem following an update on my ubuntu. Actually, I do not know why, some boost packages got broken in the process and I did not notice it. I used repaired them and the issue disappeared!

**Comment by Anais-A** [comment]
I think so. Thank you very much!
