### ISSUE TITLE
GCC 4.8 Requirement?

### ISSUE THREAD

**Issue by cecilyen** [gadgetron/gadgetron#151]
I tried to compile Gadgetron on CentOS 6 with GCC 4.4.7. But, I just realized that it required GCC 4.8. I saw the git-commit by Hansen on 3/2 to bump the GCC requirement to 4.8 in CMakeLists.txt

Is this strictly required? CentOS 6, which come with GCC 4.4.7, is still widely used in many places, especially Bruker console. This will block many users from compiling gadgetron on their system.

**Comment by cecilyen** [comment]
I cheated the CMake by changing 4.8 to 4.4 in CMakeLists.txt
But, the compilation failed on the first line.
[  1%] Building CXX object toolboxes/log/CMakeFiles/gadgetron_toolbox_log.dir/log.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [toolboxes/log/CMakeFiles/gadgetron_toolbox_log.dir/log.cpp.o] Error 1
make[1]: *** [toolboxes/log/CMakeFiles/gadgetron_toolbox_log.dir/all] Error 2
make: *** [all] Error 2

In GCC prior to 4.7, one will have to use "-std=c++0x"

**Comment by hansenms** [comment]
Hi Cecil,

Strictly GCC 4.7 is required, I think. 

We upped the requirements due to C++11. We had good reasons to make that move and while we understand that there are some older compilers that will no longer be supported, it is probably less of an issue than one might think. The release date for GCC 4.4.7 was March 13, 2012, so it is now more than 3 years old. At some point we have to stop supporting older versions. However, you don't have to compile on the Bruker console. We also have systems with older OS versions, but we don't compile on them and we simply generate a chroot image on a newer machine and run the Gadgetron chroot on the older machines. It works very well. Alternatively, you could install a newer version of GCC on the centos machine, that is an option too. You can have both installed. Finally, you don't have to run the Gadgetron on the Bruker console at all, you can run it on a nearby (networked) computer. So there are many options.

We have had multiple debates about this, recently changes were proposed to support MSVCC 6.0 (since that is the what is used on Siemens VB17), but we don't make those changes. 

At the end of the day, one of the major motivators for creating the Gadgetron was to free ourselves up from the software and hardware requirements of the vendor platforms. We would like to make sure that it remains modern.

Sorry for the inconvenience. 

Michael

**Comment by cecilyen** [comment]
CentOS 6 is the prefered Linux distro of our IT here. So, I am stuck with CentOS 6 for all my machines before our IT switch to CentOS 7. Anyway, I managed to get GCC 4.9.1 to install on CentOS 6 via software collection repo. I also successfully compiled Gadgtron from today's source. I will put the instructions in the wiki.

I do wish Gadgetron can continue to support building with GCC on Linux, because it is the most common platform for the animal MRI systems (Bruker and now defunct Varian). It is a great opportunity for these systems to catch up the reconstruction development from the clinical system an unify the raw data format. Besides, all components, like Intel MLK, NVidia CUDA, DCMTK and so on, are supported in CentOS 6 and it shall not be too difficult to support it alongside with Windows.

**Comment by inati** [comment]
Cecil,

You can build a change root image on an Ubuntu system and install it on your CentOS box.
Your Ubuntu build system can be a virtual machine.  I can help you with this off-line.

The reference Linux platform will continue to be Ubuntu LTS for the foreseeable future.  RedHat/CentOS is just too old out of the box.  Regardless, it will always possible to compile all the dependencies by hand.

Cheers,
Souheil

**Comment by cecilyen** [comment]
Souheil,

So far, I still can manage to compile Gadgetron in CentOS 6. Once the development required newer libraries than CentOS 6 or third parties can provide, I may need your help to build the Gagdtron or get a Ubuntu 14.04 VM then.

Cecil

On Apr 28, 2015, at 1:07 PM, Souheil Inati <notifications@github.com> wrote:

> Cecil, 
> 
> You can build a change root image on an Ubuntu system and install it on your CentOS box. 
> Your Ubuntu build system can be a virtual machine. I can help you with this off-line. 
> 
> The reference Linux platform will continue to be Ubuntu LTS for the foreseeable future. RedHat/CentOS is just too old out of the box. Regardless, it will always possible to compile all the dependencies by hand. 
> 
> Cheers, 
> Souheil 
> 
> 
> 
> > On Apr 27, 2015, at 11:22 AM, Cecil Yen <notifications@github.com> wrote: 
> > 
> > CentOS 6 is the prefered Linux distro of our IT here. So, I am stuck with CentOS 6 for all my machines before our IT switch to CentOS 7. Anyway, I managed to get GCC 4.9.1 to install on CentOS 6 via software collection repo. I also successfully compiled Gadgtron from today's source. I will put the instructions in the wiki. 
> > 
> > I do wish Gadgetron can continue to support building with GCC on Linux, because it is the most common platform for the animal MRI systems (Bruker and now defunct Varian). It is a great opportunity for these systems to catch up the reconstruction development from the clinical system an unify the raw data format. Besides, all components, like Intel MLK, NVidia CUDA, DCMTK and so on, are supported in CentOS 6 and it shall not be too difficult to support it alongside with Windows. 
> > 
> > — 
> > Reply to this email directly or view it on GitHub. 
> > 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Chern-Chyi (Cecil) Yen
Cell: 412-596-3697
