### ISSUE TITLE
ICE Hello World example

### ISSUE THREAD

**Issue by HDVUCAIR** [gadgetron/gadgetron#163]
I have just begun testing Gadgetron for use with our Siemens research scanners.  I managed to compile and test the "Hello, World!" example on our server.

I'm struggling at the moment to test the client side within a Siemens VB17 IDEA development environment.  I thought I would test the client by compiling the ICEGadgetron functors from the IDEA users group distribution and running it with the ICE simulator and a previously acquired Cartesian 2D TSE data set.  While the configurator completes the pipeline correctly (?), the simulation immediately fails due to various parameter errors in the original TSE functor pipeline.

Rather than post the various errors, I thought I'd ask to see if there is any documentation on a simple Hello, World one could run within the IDEA simulator to test the installation.

I'd also be interested in any ICE specific documentation.  For example, how do the Gadgetron functors work within the context of ICE memory management?  Is memory handled internally and the standard ICE raw object functor eliminated from the pipeline?  This gets to a larger question: Given that Gadgetron can be used to bypass much of the conventional ICE pipeline, what conventional functors are usually eliminated and what functors would most often be kept? 

I think an ICE Hello World might be useful to include with the next upload to the IDEA user's group.

Thanks for your help,
John Roberts.

**Comment by hansenms** [comment]
This discussion should be on the IDEA board. Or send me an email directly since I don't check the IDEA board and get no alerts when messages get posted.

We are including examples with the ICE code but unfortunately, it does not get updated as frequently as the code here because the IDEA board is pretty annoying for managing code. We upload a new version as often as we can find the time. 

The functions you would eliminate depend on the chain you are using. Sometimes nothing, sometimes a lot. The memory objects generally get eliminated when passed to the Gadgetron except when the pass through is enabled, i.e. when the data runs through both the Gadgetron and ICE recons. 

I'm closing this issue.

**Comment by HDVUCAIR** [comment]
Thanks.  I posted there.  Users there had suggested posting here since that forum might not be checked for Gadgetron questions that often.  I know some of the ICE/Gadgetron users and will try to contact one of them.

**Comment by hansenms** [comment]
Problem is that we can't discuss Siemens stuff on a public forum. We would prefer to do so, but Siemens don't allow it.

------

**Comment by HDVUCAIR** [comment]
I understand.  Thanks.
