### ISSUE TITLE
CUDA and C++11

### ISSUE THREAD

**Issue by dchansen** [gadgetron/gadgetron#233]
Is it possible that we can update to a newer version of CUDA, so we can have C++11 support?
Not having C++11 in .cu files means a ton of ifdefs in headers and makes many things much more cumbersome to write, read and maintain. In particular code using Thrust becomes so much nicer in the newer versions of C++.

From what I understand, the problem is that Siemens machines do not have a new enough driver to support new CUDA version. I am not sure why it is vital to run the Gadgetron server on Siemens though.  Why not just run it on a standard server? Or Amazon?

I have quite a bit of GPU code for the CT side which I can't merge because of this, including things that  would benefit the MRI side, such as various forms of wavelets.

Anyway, I though it would be nice to have the discussion

**Comment by hansenms** [comment]
The problem is this:

On the latest Siemens platform (VE11A), the reconstruction host (the MARS) has GPUs. Specifically it has two K10 GPUs and CUDA 5.5 with version 319.37 of the driver. If we support that version, the Gadgetron can be deployed straight on the scanner without the need for any additional hardware. That means that Gadgetron deployment is now a pure software deployment, you simply put a file on the host and off you go. That is quite powerful. It addition it it removing the need for any external hardware, it also makes the connection to the Gadgetron a local one, i.e. it never has to go on a network connection that would be limited to a 1gbit line. So if you are doing long (spiral or epi) readouts with lots of channels you don't run into problems with network bandwidth. Now the latter advantage could still be had without GPU support if we go to a newer version of CUDA and don't support CUDA on the MARS.

The setup with running directly on the MARS is currently used for interventional MRI in a works in progress package. We use the GPU for GRAPPA inversion. We do, however, have a CPU fallback for that algorithm that could run on the MARS albeit with higher latency. 

All that being said, time cannot stand still in the Gadgetron just because it does in Siemens, so at some point we have to move on. It is just a question of when the time is right for that. 

This is not really giving you an answer one way or another. It is simply saying, it is complicated. 

Thoughts?

**Comment by dchansen** [comment]
Hmm... that IS complicated. 
Two things to note: the K10 is reaching end-of-life, and while it has support for CUDA 7, it does not have support for CUDA 7.5 and will not have for CUDA 8.0 as far as I can tell. Secondly, I can't help but wonder how much of that GPU power you're using? My guess is that you're already only using 25%. Or are you doing something clever?

I'm guessing that upgrading the driver is out of the question? CUDA 7 has 98% of what we would want, so...

Another solution is to simply say that we stay with 5.5 and no C++11 support for a while yet, but allow individual toolboxes to use CUDA 7?

**Comment by hansenms** [comment]
Not sure what you mean by how much GPU power I am using? Do you mean that we could probably do pretty well with a CPU version of the GRAPPA code? In that case you are right, there is a CPU version that is not bad, but a bit more sluggish than the GPU version. So it is one option to say that on the MARS we don't support GPU. 

In any case, I am making some inquiries to figure out what the driver roadmap is within Siemens and if it is far far off in the future, we will probably just stop CUDA support on the MARS. If it is coming up soon, we will wait. 

Give me a bit of time and we will come up with a plan.

**Comment by sxg** [comment]
I'm interested in using the GTX 1080, which requires CUDA 8.0, with Gadgetron. Are there any updates planned for supported CUDA versions?

**Comment by hansenms** [comment]
I think you should be able to compile with CUDA 8.0. Did you try?

**Comment by sxg** [comment]
Not yet - I don't personally have the card. I thought this thread implied that Gadgetron wouldn't work with the latest versions of CUDA. I think I misunderstood.

**Comment by hansenms** [comment]
It should work. The discussion here is really about how far backwards we maintain compatibility with older CUDA versions. Specifically, we would really like to modernize some things and use more C++11, but older versions are not compatible, so we do the best we can. 

The newer version should work. I think some people are using CUDA 8 and we plan to update our Docker images to CUDA 8 (as soon as there are more hours in the day). 

Let us know if there are problems as you try and we will try to help fix them.
