### ISSUE TITLE
Question about gadgets

### ISSUE THREAD

**Issue by KCErb** [gadgetron/gadgetron#245]
I'm pretty new to gadgetron and really enjoying what I'm seeing around here, nice work!

My question: is there any centralization to making and distributing gadgets?

If that question doesn't make sense here's the context: 

It seems like a key concept for the gadgetron project is that researchers can create gadgets to implement into the workflow and share around similar to the Unix pipe philosophy.

I come from a Ruby background and am used to seeing community members make gems, publish them to RubyGems, and handle dependencies with bundler. 

Does gadgetron have any kind of central gadget boilerplate, gadget server, version-aware gadget dependency manager etc?

**Comment by hansenms** [comment]
Welcome to the "community"

The short answer is no, there is currently no such server.

The long answer is more complicated. The Gadgetron is not Ruby, so stuff must be compiled and binary compatibility of modules is not as straight forward to determine. There is also the issue of Mac, Windows, Linux, etc. etc. It is not to make an excuse, is just to say that making a repository of Gadgets is a pretty involved endeavor. We do however have some suggested ways of handling this:

1. If you have a set of Gadgets you would like to share, make a github repo with the code and people who want to use those Gadgets can check out your repo and compile against their version of Gadgetron installed on their system. 
2. When you have something you would like to share more broadly and it has general use, we recommend to put up a PR to have it merged into the general Gadgetron repo. 
3. When you submit stuff to the general repo, we recommend also making integration tests, so that the continuous integration system can verify that the new features stay intact over time. 

If you have a shared library with gadgets in, you can check which version of the Gadgetron they were compiled against, e.g. :

    LCE-ML01943636:~ hansenms$ gadgetron_info gadgetron_mricore NoiseAdjustGadget
    Gadgetron Version Info
       -- Version            : 3.9.1
      -- Git SHA1           : c5e253e6432026643a2b73bd13bf7bbbbf857d78
      -- System Memory size : 16384 MB
      -- Python Support     : YES
      -- Matlab Support     : YES
      -- CUDA Support       : NO

    Examining Gadget (SHARED LIB): NoiseAdjustGadget (gadgetron_mricore)
      -- Gadget compiled against Gadgetron version 3.9.1 (c5e253e6432026643a2b73bd13bf7bbbbf857d78)
        -- Properties:
          * using_cloudbus (bool): Indicates whether the cloudbus is in use and available
          * pass_on_undesired_data (bool): If true, data not matching the process function will be passed to next Gadget
          * threads (int): Number of threads to run in this Gadget
          * workingDirectory (std::string): Where to store temporary files
          * noise_dependency_prefix (std::string): Prefix of noise depencency file
          * perform_noise_adjust (bool): Whether to actually perform the noise adjust
          * pass_nonconformant_data (bool): Whether to pass data that does not conform
          * noise_dwell_time_us_preset (float): Preset dwell time for noise measurement
          * scale_only_channels_by_name (std::string): List of named channels that should only be scaled

Using this command you can automate some of the tasks involved in verifying if a certain Gadget is compatible with a certain version of the Gadgetron. 

I understand that this is not exactly what you are looking for, but I hope it helps a bit in terms of seeing where we are at. If you feel up to it, you are welcome to take on the task of creating a Gadgetron repository. We welcome contributions.

**Comment by KCErb** [comment]
Thanks for the quick response! There's not really anything that I was "looking for" just curious to see what exists / where things are at.

I'm actually very impressed that there are tools in place for checking compatibility that's a huge step in the right direction. And seeing CI here is very heartening!

I'll close this out since it answers my question. Thanks!
