### ISSUE TITLE
FFT normalization

### ISSUE THREAD

**Issue by dchansen** [gadgetron/gadgetron#43]
Currently, we have 2 seperate ways of normalizing the FFT in hoNDFFT.
Our fft functions will normalize only on the inverse fft, while the fft1, fft2, etc series of methods normalize both ways. 
We should be consistent in this, as it can produce unwanted results.

I am personally in favour of normalizing both ways, as it is much nicer from a mathematical point of view. For instance, the ifft will actually be the adjoint of the fft, and nrm2(a) == nrm2(fft(a)), which we can exploit in some of the iterative solvers. 

Either way, the cuNDFFT should be modified to have the same syntax as whatever we decide for hoNDFFT.

**Comment by inati** [comment]
I am very much in favor of this proposal.  

I know you all know this, but just to write it down….  Different FFT packages handle all of the scaling differently.  What FFTW is describe here (http://www.fftw.org/doc/What-FFTW-Really-Computes.html#What-FFTW-Really-Computes).  It does not scale in either direction, they call the operations FFTW_FORWARD and FFTW_BACKWARD.   So these are still adjoints but not inverses.  Other packages (e.g. FFTPACK, MATLAB, GSL, NUMPY) define a forward an inverse (which are not adjoints), see for example here (http://docs.scipy.org/doc/numpy/reference/routines.fft.html#module-numpy.fft).   And others do it like David is proposing where the forward and the backward are both scaled by 1/sqrt(N) and they are adjoints and inverses.

I personally prefer the symmetric form of the scaling.  If we do go with that model, then we should make it very clear in the documentation, because everyone porting their code from matlab or numpy will get it wrong.

-Souheil

**Comment by gtdeveloper5** [comment]
I would vote for the where the forward and the backward are both scaled by 1/sqrt(N) to support the SNR unit recon.

**Comment by hansenms** [comment]
I agree. We should scale in both directs so we maintain noise scaling on both forward and backward.

We might have to change some integration tests if scaling changes, but that's ok. 

Who wants to do this?

------

**Comment by dchansen** [comment]
Implemented.
