### ISSUE TITLE
Update instructions/code for new Gadget library

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#448]
The wiki pages and code for creating a new library needs a bit of updating. Specifically:
- It appears that `FindGadgetron.cmake` has some out of date paths so when a new application needs to use it, correct paths don't get set. We should make sure this script sets  ${GADGETRON_INSTALL_INCLUDE_PATH}, and associated paths. 
- The sample should install using these paths:

```
install(FILES 
    <HEADER_FILES>
    DESTINATION ${GADGETRON_INSTALL_INCLUDE_PATH} COMPONENT main)
```

and 

```
 install(FILES <CONFIG_XML_FILES> DESTINATION ${GADGETRON_INSTALL_CONFIG_PATH} COMPONENT main)
```

etc. 
- Ideally it would be nice to have a script that generates the stub files for a new Gadget library and associated CMakeLists.txt, etc. files. That way somebody could just:

```
gadgetron_make_lib <LIBNAME> <GadgetName>
```

There is a bit more to it than that (base class for Gadget, etc. etc.) but something simple is better than nothing. 
- It would be nice with a test that makes sure that this works (script, etc.).
- Run through the wiki docs and make sure everything is OK.

**Comment by tnemelc** [comment]
From my (beginner) point of view:
* The new gadget library CMakelists.txt should be modified so that the `threshold.xml` configuration file will be installed at  `/usr/local/share/gadgetron/config/` instead of `/usr/local/config/`. 
* What I did to correct cmake error during the build was to create `FindIsmrmrd.cmake` that configures CMake variables, and put it in /usr/local/share/gadgetron/cmake/.
Let me know if you're OK with that. If yes I'll submit modifications

**Comment by hansenms** [comment]
It should not be necessary to use a FindIsmrmrd.cmake script anymore since ISMRMRD now configures itself correctly. You should simply be able to do:

    find_package(ISMRMRD REQUIRED)

Without adding any Find script. That is what we do in the Gadgetron in general. Other than that, it sounds good. 

I would recommend that the location of the config files is somehow set by the FindGadgetron.cmake script since that would help if it changes again at some point.

**Comment by tnemelc** [comment]
OK, I now realize that turning Ismrmrd to uppercase at the line `find_package(ISMRMRD REQUIRED)`  the CMakeLists.txt was actually enough.

About the installation of `threshold.xml`, I suggest to use CMake variable `GADGETRON_INSTALL_INCLUDE_PATH` that will install it to `/share/gadgetron/config/` directory.

**Comment by hansenms** [comment]
I think it should be  `GADGETRON_INSTALL_CONFIG_PATH`, right?

**Comment by tnemelc** [comment]
Yes you're right! bad copy/paste :) 
I do the modification.

**Comment by tnemelc** [comment]
OK.  So far, here is what I did:
I modified wiki's page to make some changes in CMakelists.txt:
* find_package(Ismrmrd REQUIRED) is now find_package(ISMRMRD REQUIRED)
* if variable GADGETRON_INSTALL_CONFIG_PATH does not exist it is created to point on 
/usr/local/share/gadgetron/config/
* threshold.xml is installed at /usr/local/share/gadgetron/config/

It works.

However, FindGadgetron.cmake (or any.cmake) does not create `GADGETRON_INSTALL_CONFIG_PATH`.
I can set it manually in FindGadgetron.cmake, but same will happen if you decide to change its place. 
Since the original variable is set in the git repository at `/gadgetron/cmake/CMakeLists.txt `,  maybe the good way would be to operate a modification in this file so that it writes variable into `FindGadgetron.cmake` when running CMake. 

Of course this change won't operational on the actual docker image.

What you say?

**Comment by hansenms** [comment]
I think the changes should be made to the FindGadgetron.cmake file in gadgetron/cmake/FindGadgetron.cmake so that when runnning this file, it sets the relevant PATHs. It is true that if the location changes, it would have to be changed in booth the toplevel gadgetron cmake file and in the FindGadgetron.cmake script, but that is OK. At least people developing libraries will not need to know about that. 

So do you want to make a pull request to update the FindGadgetron.cmake script. I think there may be a couple of other things that could be fixed too?

**Comment by tnemelc** [comment]
I was waiting your answer about changing CMakeFiles before make my pull request. Except my modification on FindGadgetron.cmake there is no change.

**Comment by hansenms** [comment]
I made a comment to the PR, could you check that?

**Comment by tnemelc** [comment]
Yep I just sent you a new one
