### ISSUE TITLE
load balancing in Gadgetron

### ISSUE THREAD

**Issue by tharagireesh** [gadgetron/gadgetron#482]
Hello all,

By referring the following links, [https://pdfs.semanticscholar.org/fe17/e8447cdb99a84c9854d76e8adfc2571fc686.pdf](url) and [http://ieeexplore.ieee.org/document/4814179/](url)
I understand traditional pipeline architectures suffer from load imbalances when the computation work included in different pipeline stages is not perfectly balanced.
Does the architecture followed in Gadgetron takes care of this load imbalance? If yes, I would like to know how? The papers mentioned above propose a Master-Worker solution to pipeline computation for handling load imbalance.

Thanks.

**Comment by hansenms** [comment]
Not really sure what you are trying to get at here. I have not read those papers (and don't have time right now), but traditional pipeline considerations probably don't apply since much of MRI recon efficiency depends on how the data is fed into the pipeline and what accumulations are needed to make meaningful reconstructions. In any case, when you say "load imbalance" do yo mean that not all Gadgets are doing the same amount of work? They are not supposed to. So I am not sure what your concern is and what your question actually is. You will probably have to be more specific. Are you trying to solve a specific problem or are you just applying some theoretical analysis for the sake of it? Could you be more specific. 

If you have specific observed performance problems with examples that we need to address and if you have proposed solutions, could you please outline them?

**Comment by tharagireesh** [comment]
Thanks for the reply. I am into the development of MR image reconstruction software and trying to find a suitable architecture for development. I have gone through the documentation of Gadgetron and data processing pipeline architecture. I installed gadgetron and run some reconstruction pipelines. I am not conducting any performance analysis on gadgetron. 

While exploring the pros and cons of pipeline architectures in general, I studied something on issues related to load imbalance. I can explain what I understood from the previously mentioned papers with respect to gadgetron.

Suppose we have 4 gadgets Gad1, Gad2, Gad3, Gad4 in a reconstruction pipeline and definitely the workload of these four gadgets will differ.
![q](https://cloud.githubusercontent.com/assets/5310634/23303550/4f4bc47e-fab2-11e6-8586-1e90b096accf.png)

 If the computation work performed by Gad2 is heavy and takes a lot of time compared to other three gadgets, the input queue of Gad2 may be comparatively full while the other three gadgets will be free. This is referred by the term load imbalance. Is this an inherent problem within pipeline architecture? Is this not a relevant problem in MR image reconstruction?  I am new to both MRI and C++ development. Please excuse if not relevant to MR reconstruction.

**Comment by hansenms** [comment]
Well, you are assuming that the same amount of computational resources are employed at all stages of the pipeline, so let's say your busy gadget uses 4 times the number of clock cycles to complete its tasks, but the algorithmic steps are actually implemented multithreaded so that 4 threads perform the work, then it would not be imbalanced. Let's say Gad2 does an SVD on some data, but it uses MKL (multithreaded to do that). So theoretically imbalances can (and probably will occur), but it doesn't have to be so. You are also assuming that the same number of packages are processed at all steps, which is not generally true, because we have accumulation of data at certain steps. That is just considering pipelines in general. 

On the specific case of MRI reconstruction, there are other things to consider such as the fact that data is acquired at a certain rate.  Specifically, high performance reconstruction deals with the fact that not all data is available when the reconstruction starts and it maybe unknown how much data will arrive. Lots of prototype reconstruction software assumes that all data is available from the start, but such reconstruction strategies don't work well in a production setting. It is bad to wait until the end of a 5 minute acquisition before reconstruction starts. Pipeline architectures help enforce designs where processing starts as soon as possible and downstream steps start when data packages are available. 

There is a lot of theoretical (and practical) work on using networked nodes instead of pipelines and there is certainly some merit to that approach over the pipeline architectures at least in terms of saturating the available CPU power and performance, but imbalances can still occur when certain nodes are not implemented as efficiently as possible. Moreover, those node networks require (to be efficient) that the full scope of the reconstruction (say how many slices need to be reconstructed) is know before the network is formed and while that is often true, it is not always so. Think for example of real-time interactive imaging or something like navigator gating where data may be rejected and reacquired. So a functional or node network approach has a lot of theoretical appeal and can work great for a lot of cases, it is the corner cases that are hard in such frameworks. I did some experimentation with that early on, but decided to abandon it in favor of our current strategy. 

On balance the pipeline architecture is flexible and enforces high performance strategies and designs when used correctly. Can it be imbalanced and poorly utilized, sure, but it can also work very well if handled properly. It is however not the only valid or useful strategy, it is just one of many possibilities.

**Comment by hansenms** [comment]
@tharagireesh unless you have any further comments on this, I will close the issue??

**Comment by tharagireesh** [comment]
You may please close the issue. Thanks for the explanation.
