### ISSUE TITLE
gadgetron throws std::logic_error "basic_string::_S_construct null not valid"

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [gadgetron/gadgetron#596]
When starting gadgetron, I get this error message:

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Abort

Commit e7eb430673eb3272e8a821b51750c0a2a96dafed works ok.

**Comment by xueh2** [comment]
Hi Kris,

Gadgetron integration tests are green.

We had a recent change to add support for ISMRMRD waveform dataformat. It requires to add a new reader in the xmls:

<reader><slot>1026</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdWaveformMessageReader</classname></reader>

Not sure this is related to your error.

Regards
Hui

**Comment by KrisThielemans** [comment]
This happens when the `GADGETRON_HOME` variable isn't set. Before eed43130147fd41f22973a6cea65bee40ea215c1 by @dchansen , on Linux the location of the executable was checked. That commit removed that facility (and we were relying on it as it's one less configuration to do).

It's up to you if you want to check the location of the executable of course, but it shouldn't crash out without diagnostics. (I don't see what's wrong in the code).
