### ISSUE TITLE
Node Discovery

### ISSUE THREAD

**Issue by hansenms** [gadgetron/gadgetron#656]
When running a distributed version of the Gadgetron, i.e. using the distribute and collect gadgets to parallelize jobs over multiple Gadgetron instances, the DistributeGadget needs a way to know where to send data. In the current implementation, there are two ways of doing that:

1. Using the CloudBus
2. Send all data to an (assumed) load balanced endpoint and let the networking infrastructure deal with appropriate load balancing. 

The first option is problematic because the CloudBus interacts with the CloudBusRelay, which is buggy and outdated architecture. It is known that on occasion a Gadgetron instance will crash and although the connection with the relay is severed, the registration in the relay is not removed and so there is a "dead entry" in the list of nodes. That is just one of the issues. 

The second option is potentially problematic because networking based load balancing will tend to follow pretty trivial schemes, e.g. round robin, and consequently if one node is busy doing a job, it could get another even if a "free" node is available to take the job. Of course, if you have great load balancing that is very clever in your cluster, then it would take that into account, but in general, this sort of endpoint would just be something like HAProxy or a Service in a Kubernetes cluster and they are not that clever out of the box. 

So what to do?

Ideally there would be a generic scheme for discovering nodes that is configurable based on the environment that the Gadgetron is deployed. This could be done in a couple of ways:

1. An environment variable could define a script (something that gets executed with `std::system(...)`) and the `stdout` of the script would be a list that could be parsed and used by the DistributeGadget
2. An environment variable defines a URL (e.g., https://nodediscovery.mycluster.local/gadgetron/nodes`) that produces the list when issuing a `GET https://nodediscovery.mycluster.local/gadgetron/nodes`.

In either case, the list of nodes should include, id of the node, IP address, port, rest port, number of ongoing reconstructions, etc. and be in some well defined format, e.g.,

```json
{
   "version": "1.0.0",
   "nodes": [
        {
             "id": "SOME-ID",
             "ip": "IP-ADDREESS",
             "port": 9002,
             "rest-port": 9080,
             "active-reconstructions": 0,
             "has-gpu": true,
             "more-properties": "..."
        }
   ]
}
``` 

Personally, I like option 2. the best, but option 1 might be more practical because it does not necessarily require that some kind of REST endpoint is implemented. It would for instance be possible to implement node discovery by simply having the Gadgetron write into a shared storage location (a heart beat) every so often, and the script would then consume this data and produce the list. It would also not exclude option 2, since the script could simply call the endpoint. Of course, one could implement both options with little or no difficulty.

So what would we need to do this:

1. Decide on the format of the list. I think the more modern JSON approach is preferred, but we actually don't have a JSON parser in the Gadgetron (there is some stuff in the CROW thing we have included, but that should potentially be revisited and eliminated), so we would need to have a plan for that. I think a generic capability in the Gadgetron to invoke REST methods and parse the JSON (or XML) that comes back is something that should be considered. 
2. Decide on options 1,2, or both above and forge ahead. 
3. Eliminate the CloudBus. This will be a delicate operation because in addition to providing an interface for node discovery, it also keeps track on the individual node status, e.g. the CloudBus keeps track of how many reconstructions are active on the node and this information is needed for load balancing and for shutting down nodes in an orderly fashion.

@kristofferknudsen, @dchansen, @xueh2, please comment.

**Comment by kristofferknudsen** [comment]
I'll throw in my thoughts so far, such as they are. I'll mix up the ordering, and start with item two, because the choice we make there has a lot of influence on the specific format we should go with. 

2. While I consider the two options (external executable vs. querying a URL) roughly equal for complicated (load balanced, auto scaling) deployments, delegating to an external executable has clear advantages in simple deployments (static cluster, local testing, etc.). I am also reasonably sure that the external executable will be much easier to implement, and much easier to implement correctly. Should we chose the url option, we would accept some fairly complicated tasks:
- Authentication and token management. We can easily support simple Bearer tokens, but what if someone needs access to a different header? Would we be responsible for refreshing access tokens when they expire? Non-oauth authentication? We need to expose a fairly complicated configuration interface, and propagate settings correctly to the produced HTTP(S) requests, if we are to provide node discovery that works well in just most use cases. 
- Error Handling. How often should we retry? Do we respect 3xx response codes? Do we back off from 429's? How do we handle bad TLS/SSL certificates? Implementing a simple HTTP client is easy, but being well behaved takes considerably more effort. 
- Testing. Testing would involve spinning up ReST servers. As would other simple use cases. Not much work these days, but it's 30 lines of Python compared to just `cat`'ing a simple file. Easy as ReST servers are, the competition offers literally no work - no code. 

1. I don't much care about the format, as long as it is simple. Secondary concerns could be raised (no additional build dependencies, easily produced by shell scripts), but I'd be happy with all of: CSV, xml, json, edn, etc. I would prefer edn, but suggest json. 

3. I don't have much to add - I'm looking forward to it though :)

**Comment by hansenms** [comment]
@kristofferknudsen, thanks for the comments. I can give it a go to implement something. Here are some thoughts in terms on implantation (in no particular order). Please comment and voice concerns:

1. I propose making a new toolbox: `nodediscovery`, to facilitate a subsequent clean break from cloudbus. 
2. I will use an environment variable `GADGETRON_NODEDISCOVERY` to specify the command to be executed with `std::system(...)`
3. I will use JSON as the format from the output. 
4. I will use `boost::property_tree` to deserialize the output of the commend. It is a sort of new dependency, but we already use boost and this one is header only. I prefer this over implementing our own parser. 
5. I will modify CloudBus so that if `GADGETRON_NODEDISCOVERY` is set, it will be used to get the list of nodes.

Let me know if you have questions/comments/concerns about the approach.

**Comment by hansenms** [comment]
@kristofferknudsen, I have created PR #664 with the first implementation. Please review.
