### ISSUE TITLE
node_discovery needs boost/process but boost version not checked?

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#671]
We're getting compilation failures on recent gadgetron which seems to be because our boost is too old.

https://github.com/gadgetron/gadgetron/blob/fefc94ffd7234120978a5434ff4a2ef5fdae8243/toolboxes/node_discovery/node_discovery.cpp#L7 introduces the needs for `boost/process.hpp`, but this is only [introducted in boost version 1.64.0](https://www.boost.org/users/history/version_1_64_0.html). This therefore needs a check in the relevant CMakeLists.txt.

**Comment by xueh2** [comment]
Hi, 

I got the same error too under ubuntu 16.04. I found a solution is to compile your own boost:

# Compile boost
RUN cd /opt && \
    wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz && \
    tar -xzvf boost_1_67_0.tar.gz && \
    cd boost_1_67_0 && \
    ./bootstrap.sh --with-python=/usr/bin/python3 --prefix=/usr && \
    ./b2 -j$(nproc) address-model=64 stage && \
    ./b2 install && \ 
    cd /opt && rm -rf ./boost_1_67_0


Here is the code snipet from 16_04 docer file. 

regards

Hui Xue

**Comment by xueh2** [comment]
Actually i tried to add cmake check for node_discovery, but it turns out not easy to do, since this module is key and used in more than a few places.

**Comment by hansenms** [comment]
Hmmm....let me have a look.

**Comment by hansenms** [comment]
@xueh2 (and @dchansen) let me run a few things by you here. First of all, what is the current "reference" platform for Gadgetron, is it Ubuntu 16.04 or 18.04? It is something worth considering and being clear about. It matters in the context of whether this is a big problem or a wont fix. 

In any case, for the purposes of getting through this, we can do one of the following:

1. Replace the use of boost/process with ACE_Process. I would not recommend that, we are trying to off ACE, so that would be a step backwards. We could conditionally fall back on ACE_Process based on boost version but it creates two code streams that we are not testing.
2. use std::system(...) and capture the output in a file and read the file back in. It is brittle and slow and I would not recommend it. 
3. Do a check for `Boost_VERSION >= 1.64.0` and only compile `node_ discovery` when true. You say that is difficult because it "used in more than a few places". I am not sure I get that. It is used in CloudBus and we could only conditionally included it and it is used in the test for `node_discovery`, which again we could chose to include or not based on version. Is that really a big deal?

Let me know what you think and I can put up a fix. Overall though, my recommendation would be to say that a) 18.04 is the supported reference platform, and b) if you want to use 16.04, you need to update boost. We are already implicitly saying that by doing exactly that in the Dockerfile for 16.04. I am wondering what else breaks if you don't have a newer version of boost, something must have motivated that change?? *If the requirement is a certain boost version then the fix is to make that explicit in the root CMakeLists.txt and fail to build with older version.*

Also @KrisThielemans, please weigh in. Thoughts?

**Comment by xueh2** [comment]
I agree with the plan 👍 
a) 18.04 is the supported reference platform, and b) if you want to use 16.04, need to update boost

CMake file can reflect this by failing out for older boost version


We can still maintain the 16.04 docker file for some time.

**Comment by hansenms** [comment]
I have put up a PR to check the boost version.

**Comment by KrisThielemans** [comment]
ok. This PR enforces boost 1.64.0 or more recent. I understand there will be no attempt to support older boost versions. This is fine for us, we will upgrade our boost requirement then as well. Thanks.

**Comment by KrisThielemans** [comment]
Actually, our reference platform is currently still Ubuntu 16.04 (although everything works on 18.04 as well). I'd therefore like to vote to for @dchansen's option 3 
> check for `Boost_VERSION` >= 1.64.0 and only compile `node_discovery` when true.

@xueh2 , is this a major hurdle?

**Comment by xueh2** [comment]
Hi Kris,

I am not against this option either. But someone may need to do the code changes?

Regards

Hui

**Comment by hansenms** [comment]
I have put up a new PR #675, which does the conditional include, however, I would encourage the team to think very carefully about it before merging. I felt compelled to put the code up since, it is my code that created this situation, so I wanted to at least provide a fix, but I don't actually think it should be merged.

At the moment, it appears that the project has already decided that there is a need for a newer Boost version and hence it was included in the 16.04 Docker images. So there must be other code that would need similar treatment and I think it is a mess. The question is not *if* 16.04 should be deprecated, it is really a question of *when*. How long do you want to wait? 1 month? 3 months? 6 months? a year? And as the "fixes" and conditional code hacks grow so does the work of removing all of these hacks when you finally make the decision that it is time to move on. 

My position is based on the fact that the Gadgetron has long had a philosophy of using the Ubuntu LTS versions as reference standard and move to the next one as soon as people have time to do so after it is released. Possibly wait for the LTS X.X.1 version, but other than that move on. It comes as a surprise to nobody, it happens every two years. Dependent projects have plenty of fair warning, it is a scheduled upgrade. 

So my recommendation stands, I would label this "wont fix". That being said, the fix is in the PR if you want to go that route.

@KrisThielemans could you try to compile with the branch I put up and see if it even fixes your situation.

@xueh2 and @dchansen  this is really your decision.

**Comment by xueh2** [comment]
These are very nice points !

I vote for moving officially to ubuntu 18.04 and still post an ubuntu 16.04 installation guide with boost compiled. 

So if someone want to do 16.04, they could easily compile boost.

We can still keep docker file of 16.04 since it is working anyway.

**Comment by dchansen** [comment]
I think 18.04 should be our official platform, keeping in line with supporting the latest Ubuntu LTS.

There are ppa repositories for all the updated dependencies if you want to compile on 16.04, and deployment can happen via docker as always.

**Comment by KrisThielemans** [comment]
Seems you all agree then, so we will adapt our code.

@hansenms if you don't mind, I'm then not going to test your PR.

thanks all!
