### ISSUE TITLE
libatlas-base-dev required on Linux

### ISSUE THREAD

**Issue by KrisThielemans** [gadgetron/gadgetron#729]
We attempted to make a docker build on Ubuntu 18.04 without installing 
`libatlas-base-dev` as it's not listed on 
 [List of Dependencies](https://github.com/gadgetron/gadgetron/wiki/List-of-Dependencies) nor 
https://github.com/gadgetron/gadgetron/wiki/Linux-Installation, but that makes tests fail:
```
...
3: 1: [  FAILED  ] 2 tests, listed below:
3: 1: [  FAILED  ] hoNDArray_blas_Cplx/0.nrm2Test, where TypeParam = std::complex<float>
3: 1: [  FAILED  ] hoNDArray_blas_Cplx/2.nrm2Test, where TypeParam = Gadgetron::complext<float>
```
Some more info on
https://github.com/CCPPETMR/SIRF-SuperBuild/pull/214#issuecomment-468503112

**Comment by dchansen** [comment]
Hi Kris,

This is certainly a bug, and a somewhat worrying one at that.  To be clear, Gadgetron should not require libatlas, but only a BLAS and CBLAS implementation, such as the ones provided by OpenBlas, Netlib, ATLAS or MKL.
I am honestly not quite sure what is happening here, as the SuperBuild log is not an easy thing to parse. As far as I can tell, the failing build also installs libatlas-base-dev, so I think that might be a red herring?

My best guess is that the CBLAS and BLAS implementations are somehow mixed, so you might be linking against libopenblas.so and libcblas.so (rather than libblas.so and libcblas, or just libopenblas.so). 
Obviously this should not happen - FindBLAS and FindCBLAS should find the matching .so files. 

We're in the process of beta testing Gadgetron 4.0, which includes a rewrite of large parts of our CMake. I will ensure that this issue is fixed in that release.

**Comment by KrisThielemans** [comment]
thanks. we'll just install it and get on for now. I think this should be easy for you to reproduce without the superbuild in a fresh docker container but it's always hard to know where the problem comes from of course. Good luck with v4.0!
