### ISSUE TITLE
Huge memory use during transfer to Matlab (using Bucket_to_Buffer)

### ISSUE THREAD

**Issue by aTrotier** [gadgetron/gadgetron#850]
Just want to open this issue for later. (maybe it should go to gadgetron-matlab)

This issue was first described in this [closed issue](https://github.com/gadgetron/gadgetron/issues/808)

from @kristofferknudsen 
> First up is the memory use during transfer to Matlab. It appears Matlab needs several times the space of the incoming item. For very large items (for instance a 23.4 GiB buffer), this becomes significant. I consider this an issue .

**Comment by hansenms** [comment]
@aTrotier I am not sure how actionable this issue is in the Gadgetron? Could you elaborate a bit on what you would like to see fixed in the Gadgetron on this? I understand Matlab uses a lot of memory and that is regrettable, but is there something specific we can do here? Or on the gadgetron-matlab project? If there is nothing to do in either place, I say we close it. If there is something to fix in the gadgetron-matlab project, then let's move this over there. If there is something to do here, then let's get it described. Is it a bug? If so, how is it broken, how do we reproduce it? If it is something that could be enhanced, let's see if we can figure out what needs to be done. I fear this is one of those issues which will sit there for 5 years otherwise.

**Comment by aTrotier** [comment]
I think you can close it for now. I am mostly working from with acquisition rather than bucket it is faster that way (I think @ojosephs is also doing that. If someday I am facing the issue again I'll reopen that with the corresponding dataset.

**Comment by hansenms** [comment]
Thanks @aTrotier. Let's close for now and reopen when it bubbles up again.
